### ISSUE TITLE
No error message when redis is not installed

### ISSUE THREAD

**Issue by PanJ** [jitta/spinal#1]
Hi there!

Great framework indeed. I just solved some problem when I tried to use Spinal's queue feature. I can setup worker successfully even though redis is not installed, which will throw `Service queue unavailable on this broker` error when trying to queue a job, which is not quite comprehensible error message.

This is minor issue though. Will try to submit PRs if I have time. Keep up the good work, Jitta!

**Comment by hunt** [comment]
Actually Spinal doest really want to require Redis as default in some case we might just want a simple microservice. But I agreed that the error message might not clear so I just updated `README.md` and put some note on.

PS. In the near future we may want just only a cache without queue system - so how the message should be?

**Comment by PanJ** [comment]
@hunt I think Spinal should use Redis's default port (6379) as a default value for `redis` option. 

Then throw error message like `Redis not found on port 6379. Please either install and run Redis server or specify the port in broker option.` when user tries to

1. Start a worker
2. Create a job
3. Respond with `res.cache`
4. Call an action with `cache_id `
