### ISSUE TITLE
Broken in npm 3.x

### ISSUE THREAD

**Issue by PanJ** [jitta/spinal#7]
Spinal is now broken in npm 3.x because of [flat dependency](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat). [Relative](https://github.com/jitta/spinal/blob/master/lib/broker.js#L9-L10) node_modules `require` will no longer work.

**Comment by hunt** [comment]
Thank you so much!
We released with v0.4.11
https://github.com/jitta/spinal/commit/f5bbd5d658e6a02136913b54b07e9f97c909cbd6

**Comment by hunt** [comment]
Thank you so much!
We released with v0.4.11
https://github.com/jitta/spinal/commit/f5bbd5d658e6a02136913b54b07e9f97c909cbd6
